if: tag IS blank
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=slashe
  - secure: h2Vq0XyLBs12P5aDk1W5cEVbxX0KDmRkADD/Q1JdYs91i/ygvnprsH8e3DKraT5mFMVsx2hbuIsRUeaaPwLUFLfuN2O4ecxZ1rtJDsuH5A1S/tkA8uQxRQJtmLYsmOaTx7TPJKoOEg9CB63bDWlY4aB1+5Wlp7xZ8aKE+K0sZG2t//fTkC5LrklTM7GSfWB+CBEAj942M4MFQ+0PEuUIs5BdFywvbDeXMLYACknYyQmCYpOvr8ZwKbwhjMebt0zsyp3Fs/LElPPCvkmvczsgaPn1fECGOAMXE7ht5YRd4Dhp3s+y6/N8V8J69Jm9gng+75QNGoGCiifvalOA2vVBHVUGFKEcs0dzpp6TZZB5z1R18gGKPADNfwA2/ML+0Mhts3DnE85BqAmhLdZ2+7Bb2peptKDKIXKqjOHpwo31Ur0MSRv2nuNJSpSJk1K/+/Vt6mQFATWIrkYctWpHLQNQJ+Q317y6itWXu87PoYSOE2k3KFNWzIrjGMmuUh+5XKdaLnG/1bApd5c5ylTFXRWS8xkh0glBuYjde2k2I4cmAS5DsgMBVIPIAEd8cO1DP5eS4eOlWaGai20DzALERxKm3+a6BNQDKLaJoYknLQl9Pht0ICwt33umx+vEEUChm12bI5wgIouB4XcQ2QfqMYr9XH4LU62GZ2A6caOnOQ+msBE=
  - secure: QrHPIkSp1bcnM2sqrXTfCack5/1GC3AjIXpy6yyrUbJowttua8I+eGWF/0IMIWumFwxS+PwaPrkb6XnkpSRHQzJGj4iSTwSY9X4mAncf0mdQyNZpSfCtc9OwOvzIimk/MEots+vs9aJdFuNuMBLyqPTP2G98r4ZUsPrc0uOdOSCFFomKrG254L/1uTpuq00AUcZECqTR0mMzURhOyPZ8foF/SCVvKg8JsN6DQxvavNzrxx2WUfUXoKxYRyNHBoAeVNgmq7myVORIh1eIocrll4E1hlaP/ikT2mKPJJ8zmvrUgeIddITrUEqxRPxqNWjAAjuSFZGIJHBVHKbn7dvg778OdzDFx++xsUSAsC/jVlBDxugV1Miijo7LEPITCFZnFL2DF+e5564uEpkq2YU0tmK9JGlxdqstI3Ag1NliHAp4qKDaFZ6myv8IKbL8yBD8IcXdJh0/SosWrzL0nxyBhtZQ9VLB+ZN0lV4tZ6cFWaDEuGdQAVsntfgNQ++e4i3wZ0Ti0avaWBTljcMRivHhXvE5jabnK0T3oQ/64STz+fqknsKJL2ubA30tSPwkg4VpEOl0mGcG8y12PR0Ee61hVU3pHxscCc85RbBh9AxEJzErxaocH/IpXNy/6UFl9dAKWAUZtJh3/ITLnODAfyE87QuavAnEzDZ323Kr/9jORqg=
script:
- git checkout master
- version=$(npm version patch)
- docker build --tag $REGISTRY_USER/docker-nginx:$version .
after_script:
- docker images
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker push $REGISTRY_USER/docker-nginx:$version
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git add .
- git tag $version -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER [skip
  ci]"
- git commit --amend -m "TravisCI build $version [skip ci]"
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-nginx.git
  --all
- git push --repo=https://$GITHUB_PERSONAL_ACCESS_TOKEN_FOR_TRAVIS@github.com/m-slashe/docker-nginx.git
  --tags